#ifndef __INC_METIN_II_DB_QID_H__
#define __INC_METIN_II_DB_QID_H__

enum QID
{
    QID_PLAYER,				// 0
    QID_ITEM,				// 1
    QID_QUEST,				// 2
    QID_AFFECT,				// 3
    QID_LOGIN,				// 4
    QID_SAFEBOX_LOAD,			// 5
    QID_SAFEBOX_CHANGE_SIZE,		// 6
    QID_SAFEBOX_CHANGE_PASSWORD,	// 7
    QID_SAFEBOX_CHANGE_PASSWORD_SECOND,	// 8
    QID_SAFEBOX_SAVE,			// 9
    QID_ITEM_SAVE,			// 10
    QID_ITEM_DESTROY,			// 11
    QID_QUEST_SAVE,			// 12
    QID_PLAYER_SAVE,			// 13
    QID_HIGHSCORE_REGISTER,		// 14
    QID_PLAYER_DELETE,			// 15
    QID_LOGIN_BY_KEY,			// 16
    QID_PLAYER_INDEX_CREATE,		// 17
    QID_ITEM_AWARD_LOAD,		// 18
    QID_ITEM_AWARD_TAKEN,		// 19
    QID_GUILD_RANKING,			// 20

	// MYSHOP_PRICE_LIST
    QID_ITEMPRICE_SAVE,
    QID_ITEMPRICE_DESTROY,
    QID_ITEMPRICE_LOAD_FOR_UPDATE,
    QID_ITEMPRICE_LOAD,

#ifdef __PREMIUM_PRIVATE_SHOP__
    QID_PRIVATE_SHOP,
    QID_PRIVATE_SHOP_ITEM,
    QID_PRIVATE_SHOP_SAVE,
    QID_PRIVATE_SHOP_DELETE,
    QID_PRIVATE_SHOP_ITEM_SAVE,
    QID_PRIVATE_SHOP_ITEM_DELETE,
    QID_PRIVATE_SHOP_SALE,
    QID_PRIVATE_SHOP_SALE_SAVE,
#endif

#ifdef ENABLE_OFFLINE_SHOP
	QID_OFFLINESHOP_ADD_ITEM,
	QID_OFFLINESHOP_EDIT_ITEM,
	QID_OFFLINESHOP_DELETE_SHOP,
	QID_OFFLINESHOP_DELETE_SHOP_ITEM,
	QID_OFFLINESHOP_REMOVE_ITEM,
	QID_OFFLINESHOP_CREATE_SHOP,
	QID_OFFLINESHOP_CREATE_SHOP_ADD_ITEM,
	QID_OFFLINESHOP_SHOP_CHANGE_NAME,
	QID_OFFLINESHOP_SHOP_UPDATE_DURATION,
	QID_OFFLINESHOP_SAFEBOX_DELETE_ITEM,
	QID_OFFLINESHOP_SAFEBOX_ADD_ITEM,
	QID_OFFLINESHOP_SAFEBOX_UPDATE_VALUTES,
	QID_OFFLINESHOP_SAFEBOX_INSERT_VALUTES,
	QID_OFFLINESHOP_SAFEBOX_UPDATE_VALUTES_ADDING,
#endif
#ifdef ENABLE_IN_GAME_LOG_SYSTEM
	QID_IN_GAME_LOG_OFFLINESHOP_ADD_ITEM,
#endif

};

#endif
//martysama0134's ceqyqttoaf71vasf9t71218
