import uiScriptLocale

window = {
	"name" : "IkonkiWindow",
	"x" : SCREEN_WIDTH - 580,
	"y" : 0,
	"width" : 400,
	"height" : 120,
	"children" :
	(
		{
			"name" : "expander",
			"type" : "button",
			"x":80,
			"y":2,
			"default_image" : "d:/ymir work/ui/btn_expand_normal.png",
			"over_image" : "d:/ymir work/ui/btn_expand_over.png",
			"down_image" : "d:/ymir work/ui/btn_expand_down.png",
		},

		{
			"name" : "ItemShopButtonAni",
			"type" : "ani_image",

			"x":308,
			"y":20,
			
			"delay" : 3,
			"images" :
			(
				"elvion/game/animated_icons/itemshop/frame_0001.png",
				"elvion/game/animated_icons/itemshop/frame_0002.png",
				"elvion/game/animated_icons/itemshop/frame_0003.png",
				"elvion/game/animated_icons/itemshop/frame_0004.png",
				"elvion/game/animated_icons/itemshop/frame_0005.png",
				"elvion/game/animated_icons/itemshop/frame_0006.png",
				"elvion/game/animated_icons/itemshop/frame_0007.png",
				"elvion/game/animated_icons/itemshop/frame_0008.png",
				"elvion/game/animated_icons/itemshop/frame_0009.png",
				"elvion/game/animated_icons/itemshop/frame_0010.png",
				"elvion/game/animated_icons/itemshop/frame_0011.png",
				"elvion/game/animated_icons/itemshop/frame_0012.png",
				"elvion/game/animated_icons/itemshop/frame_0013.png",
				"elvion/game/animated_icons/itemshop/frame_0014.png",
				"elvion/game/animated_icons/itemshop/frame_0015.png",
				"elvion/game/animated_icons/itemshop/frame_0016.png",
				"elvion/game/animated_icons/itemshop/frame_0017.png",
				"elvion/game/animated_icons/itemshop/frame_0018.png",
				"elvion/game/animated_icons/itemshop/frame_0019.png",
				"elvion/game/animated_icons/itemshop/frame_0020.png",
				"elvion/game/animated_icons/itemshop/frame_0021.png",
				"elvion/game/animated_icons/itemshop/frame_0022.png",
				"elvion/game/animated_icons/itemshop/frame_0023.png",
				"elvion/game/animated_icons/itemshop/frame_0024.png",
				"elvion/game/animated_icons/itemshop/frame_0025.png",
				"elvion/game/animated_icons/itemshop/frame_0026.png",
				"elvion/game/animated_icons/itemshop/frame_0027.png",
				"elvion/game/animated_icons/itemshop/frame_0028.png",
				"elvion/game/animated_icons/itemshop/frame_0029.png",
				"elvion/game/animated_icons/itemshop/frame_0030.png",
				"elvion/game/animated_icons/itemshop/frame_0031.png",
				"elvion/game/animated_icons/itemshop/frame_0032.png",
				"elvion/game/animated_icons/itemshop/frame_0033.png",
				"elvion/game/animated_icons/itemshop/frame_0034.png",
				"elvion/game/animated_icons/itemshop/frame_0035.png",
				"elvion/game/animated_icons/itemshop/frame_0036.png",
				"elvion/game/animated_icons/itemshop/frame_0037.png",
				"elvion/game/animated_icons/itemshop/frame_0038.png",
				"elvion/game/animated_icons/itemshop/frame_0039.png",
				"elvion/game/animated_icons/itemshop/frame_0040.png",
				"elvion/game/animated_icons/itemshop/frame_0041.png",
				"elvion/game/animated_icons/itemshop/frame_0042.png",
				"elvion/game/animated_icons/itemshop/frame_0043.png",
				"elvion/game/animated_icons/itemshop/frame_0044.png",
				"elvion/game/animated_icons/itemshop/frame_0045.png",
				"elvion/game/animated_icons/itemshop/frame_0046.png",
				"elvion/game/animated_icons/itemshop/frame_0047.png",
				"elvion/game/animated_icons/itemshop/frame_0048.png",
				"elvion/game/animated_icons/itemshop/frame_0049.png",
				"elvion/game/animated_icons/itemshop/frame_0050.png",
				"elvion/game/animated_icons/itemshop/frame_0051.png",
				"elvion/game/animated_icons/itemshop/frame_0052.png",
				"elvion/game/animated_icons/itemshop/frame_0053.png",
				"elvion/game/animated_icons/itemshop/frame_0054.png",
				"elvion/game/animated_icons/itemshop/frame_0055.png",
				"elvion/game/animated_icons/itemshop/frame_0056.png",
				"elvion/game/animated_icons/itemshop/frame_0057.png",
				"elvion/game/animated_icons/itemshop/frame_0058.png",
				"elvion/game/animated_icons/itemshop/frame_0059.png",
				"elvion/game/animated_icons/itemshop/frame_0060.png",
				"elvion/game/animated_icons/itemshop/frame_0061.png",
				"elvion/game/animated_icons/itemshop/frame_0062.png",
				"elvion/game/animated_icons/itemshop/frame_0063.png",
				"elvion/game/animated_icons/itemshop/frame_0064.png",
				"elvion/game/animated_icons/itemshop/frame_0065.png",
				"elvion/game/animated_icons/itemshop/frame_0066.png",
				"elvion/game/animated_icons/itemshop/frame_0067.png",
				"elvion/game/animated_icons/itemshop/frame_0068.png",
				"elvion/game/animated_icons/itemshop/frame_0069.png",
				"elvion/game/animated_icons/itemshop/frame_0070.png",
				"elvion/game/animated_icons/itemshop/frame_0071.png",
				"elvion/game/animated_icons/itemshop/frame_0072.png",
			),
		},
		{
			"name" : "ItemShopButton",
			"type" : "button",
			"x":308,
			"y":20,
			"default_image" : "elvion/game/animated_icons/itemshop_norm.png",
			"over_image" : "elvion/game/animated_icons/itemshop_hover.png",
			"down_image" : "elvion/game/animated_icons/itemshop_down.png",
		},

		{
			"name" : "BattlepassButtonAni",
			"type" : "ani_image",

			"x":230,
			"y":20,
			
			"delay" : 3,
			"images" :
			(
				"elvion/game/animated_icons/battlepass/frame_0001.png",
				"elvion/game/animated_icons/battlepass/frame_0002.png",
				"elvion/game/animated_icons/battlepass/frame_0003.png",
				"elvion/game/animated_icons/battlepass/frame_0004.png",
				"elvion/game/animated_icons/battlepass/frame_0005.png",
				"elvion/game/animated_icons/battlepass/frame_0006.png",
				"elvion/game/animated_icons/battlepass/frame_0007.png",
				"elvion/game/animated_icons/battlepass/frame_0008.png",
				"elvion/game/animated_icons/battlepass/frame_0009.png",
				"elvion/game/animated_icons/battlepass/frame_0010.png",
				"elvion/game/animated_icons/battlepass/frame_0011.png",
				"elvion/game/animated_icons/battlepass/frame_0012.png",
				"elvion/game/animated_icons/battlepass/frame_0013.png",
				"elvion/game/animated_icons/battlepass/frame_0014.png",
				"elvion/game/animated_icons/battlepass/frame_0015.png",
				"elvion/game/animated_icons/battlepass/frame_0016.png",
				"elvion/game/animated_icons/battlepass/frame_0017.png",
				"elvion/game/animated_icons/battlepass/frame_0018.png",
				"elvion/game/animated_icons/battlepass/frame_0019.png",
				"elvion/game/animated_icons/battlepass/frame_0020.png",
				"elvion/game/animated_icons/battlepass/frame_0021.png",
				"elvion/game/animated_icons/battlepass/frame_0022.png",
				"elvion/game/animated_icons/battlepass/frame_0023.png",
				"elvion/game/animated_icons/battlepass/frame_0024.png",
				"elvion/game/animated_icons/battlepass/frame_0025.png",
				"elvion/game/animated_icons/battlepass/frame_0026.png",
				"elvion/game/animated_icons/battlepass/frame_0027.png",
				"elvion/game/animated_icons/battlepass/frame_0028.png",
				"elvion/game/animated_icons/battlepass/frame_0029.png",
				"elvion/game/animated_icons/battlepass/frame_0030.png",
				"elvion/game/animated_icons/battlepass/frame_0031.png",
				"elvion/game/animated_icons/battlepass/frame_0032.png",
				"elvion/game/animated_icons/battlepass/frame_0033.png",
				"elvion/game/animated_icons/battlepass/frame_0034.png",
				"elvion/game/animated_icons/battlepass/frame_0035.png",
				"elvion/game/animated_icons/battlepass/frame_0036.png",
				"elvion/game/animated_icons/battlepass/frame_0037.png",
				"elvion/game/animated_icons/battlepass/frame_0038.png",
				"elvion/game/animated_icons/battlepass/frame_0039.png",
				"elvion/game/animated_icons/battlepass/frame_0040.png",
				"elvion/game/animated_icons/battlepass/frame_0041.png",
				"elvion/game/animated_icons/battlepass/frame_0042.png",
				"elvion/game/animated_icons/battlepass/frame_0043.png",
				"elvion/game/animated_icons/battlepass/frame_0044.png",
				"elvion/game/animated_icons/battlepass/frame_0045.png",
				"elvion/game/animated_icons/battlepass/frame_0046.png",
				"elvion/game/animated_icons/battlepass/frame_0047.png",
				"elvion/game/animated_icons/battlepass/frame_0048.png",
				"elvion/game/animated_icons/battlepass/frame_0049.png",
				"elvion/game/animated_icons/battlepass/frame_0050.png",
				"elvion/game/animated_icons/battlepass/frame_0051.png",
				"elvion/game/animated_icons/battlepass/frame_0052.png",
				"elvion/game/animated_icons/battlepass/frame_0053.png",
				"elvion/game/animated_icons/battlepass/frame_0054.png",
				"elvion/game/animated_icons/battlepass/frame_0055.png",
				"elvion/game/animated_icons/battlepass/frame_0056.png",
				"elvion/game/animated_icons/battlepass/frame_0057.png",
				"elvion/game/animated_icons/battlepass/frame_0058.png",
				"elvion/game/animated_icons/battlepass/frame_0059.png",
				"elvion/game/animated_icons/battlepass/frame_0060.png",
				"elvion/game/animated_icons/battlepass/frame_0061.png",
				"elvion/game/animated_icons/battlepass/frame_0062.png",
				"elvion/game/animated_icons/battlepass/frame_0063.png",
				"elvion/game/animated_icons/battlepass/frame_0064.png",
				"elvion/game/animated_icons/battlepass/frame_0065.png",
				"elvion/game/animated_icons/battlepass/frame_0066.png",
				"elvion/game/animated_icons/battlepass/frame_0067.png",
				"elvion/game/animated_icons/battlepass/frame_0068.png",
				"elvion/game/animated_icons/battlepass/frame_0069.png",
				"elvion/game/animated_icons/battlepass/frame_0070.png",
				"elvion/game/animated_icons/battlepass/frame_0071.png",
				"elvion/game/animated_icons/battlepass/frame_0072.png",
			),
		},
		{
			"name" : "BattlepassButton",
			"type" : "button",
			"x":230,
			"y":20,
			"default_image" : "elvion/game/animated_icons/battlepass_norm.png",
			"over_image" : "elvion/game/animated_icons/battlepass_hover.png",
			"down_image" : "elvion/game/animated_icons/battlepass_down.png",
		},
		#{
		#	"name" : "EventButton",
		#	"type" : "button",
		#	"x":92,
		#	"y":19,
		#	"default_image" : "arezzo/kalendarz_1.png",
		#	"over_image" : "arezzo/kalendarz_2.png",
		#	"down_image" : "arezzo/kalendarz_3.png",
		#},

		{
			"name" : "WorldbossButtonAni",
			"type" : "ani_image",

			"x":159,
			"y":15,
			
			"delay" : 3,
			"images" :
			(
				"elvion/game/animated_icons/worldboss/frame_0001.png",
				"elvion/game/animated_icons/worldboss/frame_0002.png",
				"elvion/game/animated_icons/worldboss/frame_0003.png",
				"elvion/game/animated_icons/worldboss/frame_0004.png",
				"elvion/game/animated_icons/worldboss/frame_0005.png",
				"elvion/game/animated_icons/worldboss/frame_0006.png",
				"elvion/game/animated_icons/worldboss/frame_0007.png",
				"elvion/game/animated_icons/worldboss/frame_0008.png",
				"elvion/game/animated_icons/worldboss/frame_0009.png",
				"elvion/game/animated_icons/worldboss/frame_0010.png",
				"elvion/game/animated_icons/worldboss/frame_0011.png",
				"elvion/game/animated_icons/worldboss/frame_0012.png",
				"elvion/game/animated_icons/worldboss/frame_0013.png",
				"elvion/game/animated_icons/worldboss/frame_0014.png",
				"elvion/game/animated_icons/worldboss/frame_0015.png",
				"elvion/game/animated_icons/worldboss/frame_0016.png",
				"elvion/game/animated_icons/worldboss/frame_0017.png",
				"elvion/game/animated_icons/worldboss/frame_0018.png",
				"elvion/game/animated_icons/worldboss/frame_0019.png",
				"elvion/game/animated_icons/worldboss/frame_0020.png",
				"elvion/game/animated_icons/worldboss/frame_0021.png",
				"elvion/game/animated_icons/worldboss/frame_0022.png",
				"elvion/game/animated_icons/worldboss/frame_0023.png",
				"elvion/game/animated_icons/worldboss/frame_0024.png",
				"elvion/game/animated_icons/worldboss/frame_0025.png",
				"elvion/game/animated_icons/worldboss/frame_0026.png",
				"elvion/game/animated_icons/worldboss/frame_0027.png",
				"elvion/game/animated_icons/worldboss/frame_0028.png",
				"elvion/game/animated_icons/worldboss/frame_0029.png",
				"elvion/game/animated_icons/worldboss/frame_0030.png",
				"elvion/game/animated_icons/worldboss/frame_0031.png",
				"elvion/game/animated_icons/worldboss/frame_0032.png",
				"elvion/game/animated_icons/worldboss/frame_0033.png",
				"elvion/game/animated_icons/worldboss/frame_0034.png",
				"elvion/game/animated_icons/worldboss/frame_0035.png",
				"elvion/game/animated_icons/worldboss/frame_0036.png",
				"elvion/game/animated_icons/worldboss/frame_0037.png",
				"elvion/game/animated_icons/worldboss/frame_0038.png",
				"elvion/game/animated_icons/worldboss/frame_0039.png",
				"elvion/game/animated_icons/worldboss/frame_0040.png",
				"elvion/game/animated_icons/worldboss/frame_0041.png",
				"elvion/game/animated_icons/worldboss/frame_0042.png",
				"elvion/game/animated_icons/worldboss/frame_0043.png",
				"elvion/game/animated_icons/worldboss/frame_0044.png",
				"elvion/game/animated_icons/worldboss/frame_0045.png",
				"elvion/game/animated_icons/worldboss/frame_0046.png",
				"elvion/game/animated_icons/worldboss/frame_0047.png",
				"elvion/game/animated_icons/worldboss/frame_0048.png",
				"elvion/game/animated_icons/worldboss/frame_0049.png",
				"elvion/game/animated_icons/worldboss/frame_0050.png",
				"elvion/game/animated_icons/worldboss/frame_0051.png",
				"elvion/game/animated_icons/worldboss/frame_0052.png",
				"elvion/game/animated_icons/worldboss/frame_0053.png",
				"elvion/game/animated_icons/worldboss/frame_0054.png",
				"elvion/game/animated_icons/worldboss/frame_0055.png",
				"elvion/game/animated_icons/worldboss/frame_0056.png",
				"elvion/game/animated_icons/worldboss/frame_0057.png",
				"elvion/game/animated_icons/worldboss/frame_0058.png",
				"elvion/game/animated_icons/worldboss/frame_0059.png",
				"elvion/game/animated_icons/worldboss/frame_0060.png",
				"elvion/game/animated_icons/worldboss/frame_0061.png",
				"elvion/game/animated_icons/worldboss/frame_0062.png",
				"elvion/game/animated_icons/worldboss/frame_0063.png",
				"elvion/game/animated_icons/worldboss/frame_0064.png",
				"elvion/game/animated_icons/worldboss/frame_0065.png",
				"elvion/game/animated_icons/worldboss/frame_0066.png",
				"elvion/game/animated_icons/worldboss/frame_0067.png",
				"elvion/game/animated_icons/worldboss/frame_0068.png",
				"elvion/game/animated_icons/worldboss/frame_0069.png",
				"elvion/game/animated_icons/worldboss/frame_0070.png",
				"elvion/game/animated_icons/worldboss/frame_0071.png",
				"elvion/game/animated_icons/worldboss/frame_0072.png",
			),
		},
		{
			"name" : "WheelOfFortuneButton",
			"type" : "button",
			"x":159,
			"y":15,
			"default_image" : "elvion/game/animated_icons/worldboss_norm.png",
			"over_image" : "elvion/game/animated_icons/worldboss_hover.png",
			"down_image" : "elvion/game/animated_icons/worldboss_down.png",
		},
		{
			"name" : "WheelOfFortuneRealButton",
			"type" : "button",
			"x":80,
			"y":15,
			"default_image" : "elvion/game/animated_icons/wheel_1.png",
			"over_image" : "elvion/game/animated_icons/wheel_2.png",
			"down_image" : "elvion/game/animated_icons/wheel_3.png",
		},
	),
}